export const PlaceHolderImages = [
  { id: 'garden1', imageUrl: '/huertas.jpg', imageHint: 'Una huerta comunitaria' },
  { id: 'img1', imageUrl: '/gato-naranjo.jpg', imageHint: 'Un gato naranja' },
  { id: 'img2', imageUrl: '/gato-naranjo.jpg', imageHint: 'Un gato naranja' },
  { id: 'img3', imageUrl: '/gato-naranjo.jpg', imageHint: 'Un gato naranja' },
  { id: 'img4', imageUrl: '/gato-naranjo.jpg', imageHint: 'Un gato naranja' },
  { id: 'img5', imageUrl: '/gato-naranjo.jpg', imageHint: 'Un gato naranja' },
  { id: 'img6', imageUrl: '/gato-naranjo.jpg', imageHint: 'Un gato naranja' },
  { id: 'img7', imageUrl: '/gato-naranjo.jpg', imageHint: 'Un gato naranja' },
  { id: 'img8', imageUrl: '/gato-naranjo.jpg', imageHint: 'Un gato naranja' },
  { id: 'img9', imageUrl: '/gato-naranjo.jpg', imageHint: 'Un gato naranja' },
  { id: 'img10', imageUrl: '/gato-naranjo.jpg', imageHint: 'Un gato naranja' },
  { id: 'img11', imageUrl: '/gato-naranjo.jpg', imageHint: 'Un gato naranja' },
  { id: 'img12', imageUrl: '/gato-naranjo.jpg', imageHint: 'Un gato naranja' },
  { id: 'img13', imageUrl: '/gato-naranjo.jpg', imageHint: 'Un gato naranja' },
];
